### ISSUE TITLE
Optifine Incompatibilty

### ISSUE THREAD

**Issue by SeasonalFerret** [d0sboots/EnchantmentRevealer#1]
Using OptiFine 1.8.9 HD U H7 pre (preview version): Game saves world and exits upon opening an enchantment table.

Using OptiFine 1.8.8 HD U H6 (latest stable): Enchantment table appears completely blank. Crashes when exiting fullscreen.

Crash log with Optifine H7 Preview: https://transfer.sh/BDiqY/2017-03-02-23-08-14.txt
java.lang.NullPointerException: Rendering screen

Crash log with Optifine H6: https://transfer.sh/4IJUQ/2017-03-02-23-08-49.txt
java.lang.NoClassDefFoundError: Could not initialize class io.github.d0sboots.enchantmentrevealer.ClippedFontRenderer

**Comment by SeasonalFerret** [comment]
Image from an old 2016 post:
http://i.imgur.com/4Uhkq3E.jpg

**Comment by d0sboots** [comment]
Thanks for the report! It may be a while until I get to it, though...

**Comment by SeasonalFerret** [comment]
This is such an amazing mod! If I had to choose between this and optifine, though.. 
I really love to see this fixed! Please!!

**Comment by d0sboots** [comment]
Fixed in the latest release. I only tested  OptiFine 1.8.9 HD U H7, but I'm hoping it should be fixed for other versions too. I'll try to make sure it stays compatible as I update the mod to work with newer Minecraft versions over the next few days.
